(library
 (name saturation)
 (public_name rocq-mebi.model.algorithms.saturation)
 (libraries
  rocq-mebi.utils
  rocq-mebi.terms
  rocq-mebi.model.components)
 (modules saturation)
 (wrapped false))

(library
 (name algorithms)
 (public_name rocq-mebi.model.algorithms)
 (libraries
  rocq-mebi.utils
  rocq-mebi.terms
  rocq-mebi.model.components
  rocq-mebi.model.algorithms.saturation
  rocq-mebi.model.lts
  rocq-mebi.model.fsm
  ; rocq-mebi.model
  yojson)
 (modules
  minimization
  bisimilarity
  product
  saturation_estimate
  ; similarity
  )
 (wrapped false))

(include_subdirs no)
